services:
  backend:
    image: chenseanxy/full-stack-open-phonebook-backend
    build:
      context: ./phonebook-backend
    environment:
      NODE_ENV: production
      PORT: 3001
      MONGO_ENDPOINT: mongodb://
    ports:
      - 3001:3001
  frontend:
    image: chenseanxy/full-stack-open-phonebook-frontend
    build:
      context: ./phonebook
    ports:
      - 3000:80
